# Use the official Node.js 18 image.
FROM node:18-alpine

ENV NEXT_TELEMETRY_DISABLED 1

# Create and change to the app directory.
WORKDIR /usr/src/app

# Copy application dependency manifests to the container image.
COPY package*.json ./

# Install dependencies.
RUN yarn

# Copy local code to the container image.
COPY . .

# Start the development server
CMD ["yarn", "dev"]
