apiVersion: v1
kind: Service
metadata:
  name: counter-frontend
  namespace: counter
spec:
  selector:
    app: counter-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
