apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-frontend
  namespace: counter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter-frontend
  template:
    metadata:
      labels:
        app: counter-frontend
    spec:
      containers:
        - name: counter-frontend
          image: alextebbs/counter-frontend
          ports:
            - containerPort: 3000
