apiVersion: v1
kind: Pod
metadata:
  name: jump-pod
  namespace: counter
spec:
  containers:
    - name: jump-pod
      image: alpine
      command: ["/bin/sh"]
      args: ["-c", "while true; do sleep 30; done;"]
      stdin: true
      tty: true
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "512Mi"
          cpu: "500m"
