// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: counter/v1/counter.proto

package counter

import (
	v1 "github.com/alextebbs/counters/pb/event/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Counter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title     string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Count     int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *Counter) Reset() {
	*x = Counter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_counter_v1_counter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Counter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Counter) ProtoMessage() {}

func (x *Counter) ProtoReflect() protoreflect.Message {
	mi := &file_counter_v1_counter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Counter.ProtoReflect.Descriptor instead.
func (*Counter) Descriptor() ([]byte, []int) {
	return file_counter_v1_counter_proto_rawDescGZIP(), []int{0}
}

func (x *Counter) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Counter) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Counter) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Counter) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type CounterServiceCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title      string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	EventTitle string `protobuf:"bytes,2,opt,name=event_title,json=eventTitle,proto3" json:"event_title,omitempty"`
}

func (x *CounterServiceCreateRequest) Reset() {
	*x = CounterServiceCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_counter_v1_counter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CounterServiceCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CounterServiceCreateRequest) ProtoMessage() {}

func (x *CounterServiceCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_counter_v1_counter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CounterServiceCreateRequest.ProtoReflect.Descriptor instead.
func (*CounterServiceCreateRequest) Descriptor() ([]byte, []int) {
	return file_counter_v1_counter_proto_rawDescGZIP(), []int{1}
}

func (x *CounterServiceCreateRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CounterServiceCreateRequest) GetEventTitle() string {
	if x != nil {
		return x.EventTitle
	}
	return ""
}

type CounterServiceCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Counter *Counter `protobuf:"bytes,1,opt,name=counter,proto3" json:"counter,omitempty"`
}

func (x *CounterServiceCreateResponse) Reset() {
	*x = CounterServiceCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_counter_v1_counter_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CounterServiceCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CounterServiceCreateResponse) ProtoMessage() {}

func (x *CounterServiceCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_counter_v1_counter_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CounterServiceCreateResponse.ProtoReflect.Descriptor instead.
func (*CounterServiceCreateResponse) Descriptor() ([]byte, []int) {
	return file_counter_v1_counter_proto_rawDescGZIP(), []int{2}
}

func (x *CounterServiceCreateResponse) GetCounter() *Counter {
	if x != nil {
		return x.Counter
	}
	return nil
}

type CounterServiceGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Optional: Specify an ID to get a specific counter
}

func (x *CounterServiceGetRequest) Reset() {
	*x = CounterServiceGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_counter_v1_counter_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CounterServiceGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CounterServiceGetRequest) ProtoMessage() {}

func (x *CounterServiceGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_counter_v1_counter_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CounterServiceGetRequest.ProtoReflect.Descriptor instead.
func (*CounterServiceGetRequest) Descriptor() ([]byte, []int) {
	return file_counter_v1_counter_proto_rawDescGZIP(), []int{3}
}

func (x *CounterServiceGetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CounterServiceGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Counter *Counter `protobuf:"bytes,1,opt,name=counter,proto3" json:"counter,omitempty"`
}

func (x *CounterServiceGetResponse) Reset() {
	*x = CounterServiceGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_counter_v1_counter_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CounterServiceGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CounterServiceGetResponse) ProtoMessage() {}

func (x *CounterServiceGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_counter_v1_counter_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CounterServiceGetResponse.ProtoReflect.Descriptor instead.
func (*CounterServiceGetResponse) Descriptor() ([]byte, []int) {
	return file_counter_v1_counter_proto_rawDescGZIP(), []int{4}
}

func (x *CounterServiceGetResponse) GetCounter() *Counter {
	if x != nil {
		return x.Counter
	}
	return nil
}

type CounterServiceListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CounterServiceListRequest) Reset() {
	*x = CounterServiceListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_counter_v1_counter_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CounterServiceListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CounterServiceListRequest) ProtoMessage() {}

func (x *CounterServiceListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_counter_v1_counter_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CounterServiceListRequest.ProtoReflect.Descriptor instead.
func (*CounterServiceListRequest) Descriptor() ([]byte, []int) {
	return file_counter_v1_counter_proto_rawDescGZIP(), []int{5}
}

type CounterServiceListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Counters []*Counter `protobuf:"bytes,1,rep,name=counters,proto3" json:"counters,omitempty"`
}

func (x *CounterServiceListResponse) Reset() {
	*x = CounterServiceListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_counter_v1_counter_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CounterServiceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CounterServiceListResponse) ProtoMessage() {}

func (x *CounterServiceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_counter_v1_counter_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CounterServiceListResponse.ProtoReflect.Descriptor instead.
func (*CounterServiceListResponse) Descriptor() ([]byte, []int) {
	return file_counter_v1_counter_proto_rawDescGZIP(), []int{6}
}

func (x *CounterServiceListResponse) GetCounters() []*Counter {
	if x != nil {
		return x.Counters
	}
	return nil
}

type CounterServiceIncrementRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *CounterServiceIncrementRequest) Reset() {
	*x = CounterServiceIncrementRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_counter_v1_counter_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CounterServiceIncrementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CounterServiceIncrementRequest) ProtoMessage() {}

func (x *CounterServiceIncrementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_counter_v1_counter_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CounterServiceIncrementRequest.ProtoReflect.Descriptor instead.
func (*CounterServiceIncrementRequest) Descriptor() ([]byte, []int) {
	return file_counter_v1_counter_proto_rawDescGZIP(), []int{7}
}

func (x *CounterServiceIncrementRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CounterServiceIncrementRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type CounterServiceIncrementResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Event   *v1.Event `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Counter *Counter  `protobuf:"bytes,2,opt,name=counter,proto3" json:"counter,omitempty"`
}

func (x *CounterServiceIncrementResponse) Reset() {
	*x = CounterServiceIncrementResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_counter_v1_counter_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CounterServiceIncrementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CounterServiceIncrementResponse) ProtoMessage() {}

func (x *CounterServiceIncrementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_counter_v1_counter_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CounterServiceIncrementResponse.ProtoReflect.Descriptor instead.
func (*CounterServiceIncrementResponse) Descriptor() ([]byte, []int) {
	return file_counter_v1_counter_proto_rawDescGZIP(), []int{8}
}

func (x *CounterServiceIncrementResponse) GetEvent() *v1.Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *CounterServiceIncrementResponse) GetCounter() *Counter {
	if x != nil {
		return x.Counter
	}
	return nil
}

type CounterServiceDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CounterServiceDeleteRequest) Reset() {
	*x = CounterServiceDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_counter_v1_counter_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CounterServiceDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CounterServiceDeleteRequest) ProtoMessage() {}

func (x *CounterServiceDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_counter_v1_counter_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CounterServiceDeleteRequest.ProtoReflect.Descriptor instead.
func (*CounterServiceDeleteRequest) Descriptor() ([]byte, []int) {
	return file_counter_v1_counter_proto_rawDescGZIP(), []int{9}
}

func (x *CounterServiceDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CounterServiceDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CounterServiceDeleteResponse) Reset() {
	*x = CounterServiceDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_counter_v1_counter_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CounterServiceDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CounterServiceDeleteResponse) ProtoMessage() {}

func (x *CounterServiceDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_counter_v1_counter_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CounterServiceDeleteResponse.ProtoReflect.Descriptor instead.
func (*CounterServiceDeleteResponse) Descriptor() ([]byte, []int) {
	return file_counter_v1_counter_proto_rawDescGZIP(), []int{10}
}

func (x *CounterServiceDeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_counter_v1_counter_proto protoreflect.FileDescriptor

var file_counter_v1_counter_proto_rawDesc = []byte{
	0x0a, 0x18, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2f, 0x76,
	0x31, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7f, 0x0a,
	0x07, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x54,
	0x0a, 0x1b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54,
	0x69, 0x74, 0x6c, 0x65, 0x22, 0x4d, 0x0a, 0x1c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x65, 0x72, 0x22, 0x2a, 0x0a, 0x18, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x4a, 0x0a, 0x19, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x07,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x65, 0x72, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x22, 0x1b, 0x0a, 0x19, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4d, 0x0a, 0x1a, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x08, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65,
	0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x08, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x22, 0x46, 0x0a, 0x1e, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x22,
	0x77, 0x0a, 0x1f, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x25, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x2d, 0x0a, 0x07, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52,
	0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x22, 0x2d, 0x0a, 0x1b, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x38, 0x0a, 0x1c, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x32, 0xe5, 0x03, 0x0a, 0x0e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x5d, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x27,
	0x2e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x54, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x24, 0x2e, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x25, 0x2e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x57, 0x0a, 0x04, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x25, 0x2e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x66, 0x0a, 0x09, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12,
	0x2a, 0x2e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x63, 0x72, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5d, 0x0a, 0x06, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x12, 0x27, 0x2e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x65, 0x78, 0x74, 0x65, 0x62, 0x62,
	0x73, 0x2f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x3b, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_counter_v1_counter_proto_rawDescOnce sync.Once
	file_counter_v1_counter_proto_rawDescData = file_counter_v1_counter_proto_rawDesc
)

func file_counter_v1_counter_proto_rawDescGZIP() []byte {
	file_counter_v1_counter_proto_rawDescOnce.Do(func() {
		file_counter_v1_counter_proto_rawDescData = protoimpl.X.CompressGZIP(file_counter_v1_counter_proto_rawDescData)
	})
	return file_counter_v1_counter_proto_rawDescData
}

var file_counter_v1_counter_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_counter_v1_counter_proto_goTypes = []interface{}{
	(*Counter)(nil),                         // 0: counter.v1.Counter
	(*CounterServiceCreateRequest)(nil),     // 1: counter.v1.CounterServiceCreateRequest
	(*CounterServiceCreateResponse)(nil),    // 2: counter.v1.CounterServiceCreateResponse
	(*CounterServiceGetRequest)(nil),        // 3: counter.v1.CounterServiceGetRequest
	(*CounterServiceGetResponse)(nil),       // 4: counter.v1.CounterServiceGetResponse
	(*CounterServiceListRequest)(nil),       // 5: counter.v1.CounterServiceListRequest
	(*CounterServiceListResponse)(nil),      // 6: counter.v1.CounterServiceListResponse
	(*CounterServiceIncrementRequest)(nil),  // 7: counter.v1.CounterServiceIncrementRequest
	(*CounterServiceIncrementResponse)(nil), // 8: counter.v1.CounterServiceIncrementResponse
	(*CounterServiceDeleteRequest)(nil),     // 9: counter.v1.CounterServiceDeleteRequest
	(*CounterServiceDeleteResponse)(nil),    // 10: counter.v1.CounterServiceDeleteResponse
	(*timestamppb.Timestamp)(nil),           // 11: google.protobuf.Timestamp
	(*v1.Event)(nil),                        // 12: event.v1.Event
}
var file_counter_v1_counter_proto_depIdxs = []int32{
	11, // 0: counter.v1.Counter.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 1: counter.v1.CounterServiceCreateResponse.counter:type_name -> counter.v1.Counter
	0,  // 2: counter.v1.CounterServiceGetResponse.counter:type_name -> counter.v1.Counter
	0,  // 3: counter.v1.CounterServiceListResponse.counters:type_name -> counter.v1.Counter
	12, // 4: counter.v1.CounterServiceIncrementResponse.event:type_name -> event.v1.Event
	0,  // 5: counter.v1.CounterServiceIncrementResponse.counter:type_name -> counter.v1.Counter
	1,  // 6: counter.v1.CounterService.Create:input_type -> counter.v1.CounterServiceCreateRequest
	3,  // 7: counter.v1.CounterService.Get:input_type -> counter.v1.CounterServiceGetRequest
	5,  // 8: counter.v1.CounterService.List:input_type -> counter.v1.CounterServiceListRequest
	7,  // 9: counter.v1.CounterService.Increment:input_type -> counter.v1.CounterServiceIncrementRequest
	9,  // 10: counter.v1.CounterService.Delete:input_type -> counter.v1.CounterServiceDeleteRequest
	2,  // 11: counter.v1.CounterService.Create:output_type -> counter.v1.CounterServiceCreateResponse
	4,  // 12: counter.v1.CounterService.Get:output_type -> counter.v1.CounterServiceGetResponse
	6,  // 13: counter.v1.CounterService.List:output_type -> counter.v1.CounterServiceListResponse
	8,  // 14: counter.v1.CounterService.Increment:output_type -> counter.v1.CounterServiceIncrementResponse
	10, // 15: counter.v1.CounterService.Delete:output_type -> counter.v1.CounterServiceDeleteResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_counter_v1_counter_proto_init() }
func file_counter_v1_counter_proto_init() {
	if File_counter_v1_counter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_counter_v1_counter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Counter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_counter_v1_counter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CounterServiceCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_counter_v1_counter_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CounterServiceCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_counter_v1_counter_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CounterServiceGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_counter_v1_counter_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CounterServiceGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_counter_v1_counter_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CounterServiceListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_counter_v1_counter_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CounterServiceListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_counter_v1_counter_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CounterServiceIncrementRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_counter_v1_counter_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CounterServiceIncrementResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_counter_v1_counter_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CounterServiceDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_counter_v1_counter_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CounterServiceDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_counter_v1_counter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_counter_v1_counter_proto_goTypes,
		DependencyIndexes: file_counter_v1_counter_proto_depIdxs,
		MessageInfos:      file_counter_v1_counter_proto_msgTypes,
	}.Build()
	File_counter_v1_counter_proto = out.File
	file_counter_v1_counter_proto_rawDesc = nil
	file_counter_v1_counter_proto_goTypes = nil
	file_counter_v1_counter_proto_depIdxs = nil
}
